### ISSUE TITLE
Improve OD level visualisation

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/odnet#5]
Thinking this could be improved by adding sub-titles and removing whitespace, also could transparency of desire lines help? Aesthetics varying by n. cycling?

![image](https://user-images.githubusercontent.com/1825120/149579099-0c334cf9-4c8e-4762-86c5-0daf1037c952.png)

Reckon ggplot2 or tmap code in place of this base R code could help:

https://github.com/Robinlovelace/odnet/blob/18e74ffc5d02b26756a8ac1230a4ba448911f80e/README.Rmd#L211-L228

Heads-up @rogerbeecham

**Comment by rogerbeecham** [comment]
Hi @Robinlovelace just reproducing your example. Yes should be able to do this -- will have a go at  a ggplot2 implementation.

**Comment by Robinlovelace** [comment]
Fantastic, many thanks. On the case with the routing, live scenes from my computer (one to run overnight...)

![image](https://user-images.githubusercontent.com/1825120/149587876-70ca9b37-d4f3-45bc-af12-368341bd36fe.png)

**Comment by rogerbeecham** [comment]
OK -- pull request on ggplot version reimplemented the baseR fig1. Benefits may be more flexibility in visual design and that we can also extend / take advantage of view composition. Problems downloading some of network data, but code should work.

**Comment by Robinlovelace** [comment]
Sounds like great work, although cannot see the PR?  https://github.com/Robinlovelace/odnet/pulls

**Comment by Robinlovelace** [comment]
Looking good, thanks Roger! Result from tweaked version of that code:

```r
library(sf)
library(patchwork)
sel_net = sample(nrow(network), 1000)
theme_set(theme_void())
p1 <- ggplot() +
  geom_sf(data=zones, size=.1, alpha=.3) +
  geom_sf(data=desire_lines_top$geometry, alpha=.2, size=.7)+
  coord_sf(crs=st_crs(zones), datum=NA) +
  ggtitle(names(network_filenames)[1])
  
p2 <- ggplot() +
  geom_sf(data=zones, size=.1, alpha=.3) +
  geom_sf(data=network$geometry, colour="#67000d", size=.1)+
  geom_sf(data=read_sf("output_max10k.geojson"), alpha=.2, size=.7)+
  coord_sf(crs=st_crs(zones), datum=NA) +
  ggtitle(names(network_filenames)[2])

p3 <- ggplot() +
  geom_sf(data=zones, size=.1, alpha=.3) +
  geom_sf(data=network$geometry, colour="#67000d", size=.1)+
  geom_sf(data=read_sf("output_max50.geojson"), alpha=.2, size=.7)+
  coord_sf(crs=st_crs(zones), datum=NA) +
  ggtitle(names(network_filenames)[3])

p4 <- ggplot() +
  geom_sf(data=zones, size=.1, alpha=.3) +
  geom_sf(data=network$geometry, colour="#67000d", size=.1)+
  geom_sf(data=read_sf("output_max10.geojson"), alpha=.2, size=.7)+
  coord_sf(crs=st_crs(zones), datum=NA) +
  ggtitle(names(network_filenames)[4])

(p1+p2)/(p3+p4)
```


![image](https://user-images.githubusercontent.com/1825120/149625933-a4c493ca-c122-41a0-a0ed-4b845892c0c2.png)

**Comment by Robinlovelace** [comment]
Next step: going to try to make it consistent with the subsequent graphic, with a frame of reference and general tmap aesthetic.

![image](https://user-images.githubusercontent.com/1825120/149625971-8cfea01e-a8a4-42c2-b79e-874eb1f66d21.png)

**Comment by Robinlovelace** [comment]
Progress, generated from code in the commit above. 

![image](https://user-images.githubusercontent.com/1825120/149629236-f12db28c-1efc-4a90-9db8-ca8bb2286a61.png)
